### ISSUE TITLE
Way to login for the other than GIGYA users with Magento GIGYA Extension

### ISSUE THREAD

**Issue by wgtgithub** [gigya/Magento-2#108] opened 2021-03-10 03:25 UTC
We installed Magento GIGYA Extension but we can't login user who was added by admin user of backend.
The reason is the user isn't GIGYA user.
Let me know way to login for the other than GIGYA user to Magento with the GIGYA Extension

**Comment by wgtgithub** [comment] 2021-03-11 04:37
Knock, knock, knock
Hello?

**Comment by wgtgithub** [comment] 2021-03-11 08:47
It is impossible to login and sign-up for company admin user who was added by Magento admin user at create company.

**Comment by Ynhockey** [comment] 2021-05-03 10:53
Hi wgtgithub,

Do you mean that Magento B2B features aren't synchronized with Gigya's B2B features?

Technically Gigya's B2B isn't supported in the module, but it shouldn't break existing login flows. Please elaborate on what exactly you're trying to do.

By the way, if anything is urgent, please feel free to open a support ticket :) that will insure a prompt response + any follow-ups necessary until the issue is addressed in some form.

**Comment by Ynhockey** [comment] 2022-12-29 13:34
Closed with no response in a while. Please feel free to reopen/open a new issue if this is still a problem.

**Closed by Ynhockey** 2022-12-29 13:34 UTC
